### ISSUE TITLE
Option to remove Typefully button

### ISSUE THREAD

**Issue by potch** [typefully/minimal-twitter#116]
Hello,

I just want to say that this extension literally makes Twitter usable (I do not say this as an understatement). I'd love to support your work in any way I can and understand if the Typefully integration is the best way for you to get that support, but in the spirit of "minimal" it would be great to be able to hide that button via the settings.

Either way, thank you for making such a useful extension!

**Comment by thomaswang** [comment]
@potch - makes sense!

**Comment by FoxhackDN** [comment]
Yes please. I noticed this option was added and it's just getting in the way for me. Please make it an option.
