### ISSUE TITLE
Twitter favicon shows pixelated

### ISSUE THREAD

**Issue by enderdiamond21** [typefully/minimal-twitter#125]
This extension makes the Twitter favicon all weird and pixelated. As someone with severe OCD, this is no joke remarkably close to making me want to delete this extension. PLEASE FIX IT.

**WITH EXTENSION ENABLED**
<img width="112" alt="Screenshot 2022-11-07 at 16 41 13" src="https://user-images.githubusercontent.com/64865637/200438681-4900fcd2-b2a3-48a7-8ae6-0f4acf78a3d5.png">

**WITHOUT EXTENSION**
<img width="121" alt="Screenshot 2022-11-07 at 16 42 10" src="https://user-images.githubusercontent.com/64865637/200438798-ebb9c4c0-79ca-44ed-9a20-4adf9475d46e.png">

**Comment by enderdiamond21** [comment]
WORKAROUND:

Use the [Favicon Changer](https://chrome.google.com/webstore/detail/favicon-changer/ijaabbaphikljkkcbgpbaljfjpflpeoo) extension to change the Twitter favicon back to normal.

Use this image as the replacement:
![free-twitter-logo-icon-2429-thumb](https://user-images.githubusercontent.com/64865637/200441106-1062b62d-aebe-4f0b-8694-03289b9e8e74.png)

**Comment by thomaswang** [comment]
Fixed! https://github.com/typefully/minimal-twitter/pull/126/commits/8e3c5a9ff595887de65ca1a71b6353e2170e17df
