### ISSUE TITLE
Show Labels bugs

### ISSUE THREAD

**Issue by Tageel83** [typefully/minimal-twitter#128]
Thanx 4 almost the best Twitter extension, I think latest updates cant's let labels disappear & only show on hover. Pleaze fix it.

**Comment by thomaswang** [comment]
Hi @Tageel83 thanks for the report, this is a new bug. Will prioritize this.

**Comment by thomaswang** [comment]
https://github.com/typefully/minimal-twitter/commit/df7dac42d2f85a57fbb42aa343596c4dd40deba5

**Comment by thomaswang** [comment]
https://github.com/typefully/minimal-twitter/pull/129/commits/24b51322f46f03bb0b7120c461745ff4d22734e7
