### ISSUE TITLE
Communities navigation toggle not working

### ISSUE THREAD

**Issue by Shpigford** [typefully/minimal-twitter#133]
The various navigation item toggles all seem to be working fine *except* for the Communities toggle.

This is in Arc 0.81.0, which is running Chromium 108.0.5359.125.

https://user-images.githubusercontent.com/35243/208479979-8cc50744-a801-48bc-936f-5dc31755e73a.mp4

**Comment by thomaswang** [comment]
Can you check your `...` button @Shpigford? 

I believe Twitter removed it as a default button. We can try applying the same treatment as we are the Lists button, which is also not a default button.

**Comment by Shpigford** [comment]
@thomaswang Ah! There it is. Yeah, would love it to be an option like the Lists button as I use Communities a good bit.

Thanks!

**Comment by thomaswang** [comment]
https://github.com/typefully/minimal-twitter/pull/141/commits/7d1a06ad25d9ba74ea4ec5588e54869deca0b873
