### ISSUE TITLE
Suggestion:  Remove View count

### ISSUE THREAD

**Issue by Balentay** [typefully/minimal-twitter#135]
I really don't want to know how many people saw my tweet but chose not to engage with it.  It's distracting at best, frustrating and even hurtful at worst

![35cf325f-a135-43e6-b947-d2d099ddebac](https://user-images.githubusercontent.com/37963727/209251483-60113d99-9a34-4aac-9391-3df1e7ef1e08.png)

**Comment by onkoe** [comment]
This would be an amazing change! I already despise Twitter on iPhone, but adding this to your browser extension would make me exclusively use it!

**Comment by ricardosaracino** [comment]
There is also another count when viewing a tweet

![image](https://user-images.githubusercontent.com/759253/209685073-a144c1fa-3a94-4120-b034-0893cea6e016.png)

**Comment by thomaswang** [comment]
https://github.com/typefully/minimal-twitter/commit/228ed1ff0fafb5fa162afbc58036b039581f5b21 This is available in 5.0.0.4 (shoutout @linuz90). Make sure to check off then on again for it to work (this will be fixed in next release)
