### ISSUE TITLE
Pinned Lists get removed automatically.

### ISSUE THREAD

**Issue by deadcoder0904** [typefully/minimal-twitter#139]
I think the logic for `Topics To Follow` is the same as `Pinned Lists` as I don't see anything under `Pinned Lists` at all.

URL for `Pinned Lists` is https://twitter.com/deadcoder0904/lists (try checking `Topics To Follow` to see it get removed. if you uncheck it, it works)

**Comment by thomaswang** [comment]
https://github.com/typefully/minimal-twitter/pull/141/commits/433364159227003835180294e888c34139f24c7c

**Comment by deadcoder0904** [comment]
@thomaswang it's not fixed.

see this:

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/16436270/213649952-784f37a2-d088-4811-8f51-49fc7aa65438.png">

also, can you fix suggested too after you follow someone?

**Comment by deadcoder0904** [comment]
@thomaswang not sure you've seen this?

this ain't fixed. same with suggested.

**Comment by thomaswang** [comment]
@deadcoder0904 did you try [installing latest](https://github.com/typefully/minimal-twitter/blob/main/MANUAL_INSTALLATION.MD)? (it may not be available in the stores yet)

**Comment by deadcoder0904** [comment]
oh, it was recently fixed. probably made available in store, thanks :)
