### ISSUE TITLE
Search bar not showing on Arc browser

### ISSUE THREAD

**Issue by aaronjz** [typefully/minimal-twitter#140]
Hi, 

I've been using the Minimal Twitter for Chrome on the Arc browser (Chromium). I've noticed the search bar is not showing when I've asked it to show. Curious as to why that might be. Thanks.

**Comment by thomaswang** [comment]
Hi @aaronjz it could be that you're below the `1265px` breakpoint: https://github.com/typefully/minimal-twitter/blob/main/css/main.css#L113

**Comment by aaronjz** [comment]
You are correct. I am working on a 13” screen. When I went fullscreen, I saw the search bar there. Thanks for the prompt response.

Aaron
