### ISSUE TITLE
Add an option to hide the "timeline type" overlay bar

### ISSUE THREAD

**Issue by dangpzanco** [typefully/minimal-twitter#143]
Today Twitter updated the timeline selection in such a way that:

Home -> For you
Latest tweets -> Following

Many (can't confirm if all) accounts were reset to the "For you" timeline and now there's a wasted space above the screen showing the timeline selector bar.

Please update the extension to account for this latest update.

Example:

![screenshot](https://i.imgur.com/KdSClJI.png)

**Comment by thomaswang** [comment]
Good catch @dangpzanco, added to the next release! https://github.com/typefully/minimal-twitter/pull/141/commits/ed412625faae2e9e86663a03e8ea7010a29ad9a5
