### ISSUE TITLE
Toggle to have home feed always on "Following" instead of "For You"

### ISSUE THREAD

**Issue by Hexerin** [typefully/minimal-twitter#149]
I would suggest a feature that causes the home feed to always default to "Following" instead of "For You". Refer to screenshot for clarity on what I'm referring to.

![47a30371b529242fd2e1a88a00410923](https://user-images.githubusercontent.com/42397404/213478104-903a54a4-f002-42c3-a680-3173140f8903.png)

**Comment by dangpzanco** [comment]
I think the recently added option "Show Latest Tweets (if available)" is supposed to do that (but it doesn't). I came here to open this exact issue, thanks.

**Comment by thomaswang** [comment]
Added in 5.0.2: https://github.com/typefully/minimal-twitter/releases/tag/v5.0.2
