### ISSUE TITLE
tab "Following" as homepage ?

### ISSUE THREAD

**Issue by fredmo** [typefully/minimal-twitter#152]
Dear Minimal Theme for Twitter,

This extension is fine, but could you propose an option to :

when I launch the url : https://twitter.com/home , currently it s arriving on "For You", and I need to click on "Following" to have only my following people.

Could you add a option to have automatically "Following" on the url https://twitter.com/home

Regards

**Comment by thomaswang** [comment]
Thanks @Hexerin :) yes it's in 5.0.2 — you can install the latest bundle manually if you want to have it right away: https://github.com/typefully/minimal-twitter/blob/main/MANUAL_INSTALLATION.MD

**Comment by fredmo** [comment]
Thank you .

Tested ok on firefox.
